# Generated by Django 5.2.12 on 2026-03-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['name'], 'verbose_name': 'Habit', 'verbose_name_plural': 'Habits'},
        ),
        migrations.AlterField(
            model_name='habit',
            name='frequency',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=20),
        ),
    ]
